title: Melograf Mastering
email: mail@melograf.com
description: 'Audio mastering by Christopher Leary.'
baseurl:
url: 'https://melograf.com'
twitter:
  username: ochremusic
facebook:
  app_id:
  publisher: 190149549210
  admins: 100000537844760

is_available: false

social:
  name: Melograf Mastering
  links:
    - https://twitter.com/ochremusic
    - https://www.facebook.com/melograf

# Build settings
nav:
  - title: 'Home'
    permalink: '/'
  - title: 'Process'
    permalink: '/process/'
  - title: 'FAQ'
    permalink: '/faq/'
  - title: 'About'
    permalink: '/about/'
  - title: 'Contact'
    permalink: '/contact/'

defaults:
  layout: page

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer

exclude:
  - Gemfile
  - Gemfile.lock
  - '*.sh'
  - src/
